export type Category = "heavy" | "dry" | "beverage" | "fresh" | "frozen";
export type Diet = "Tutto" | "Vegetariana" | "Vegana";
export interface Profile {
  name: string;
  diet: Diet;
  allergies: string[];
  budget: number;
  goal: string;
}
export interface Product {
  id: string;
  name: string;
  unit: string;
  price: number;
  discount: number;
  category: Category;
  node: string;
  emoji: string;
  vegan: boolean;
  vegetarian: boolean;
  allergens: string[];
  ingredients: string;
  days: number;
  available: boolean;
}
const rows: [
  string,
  string,
  string,
  number,
  Category,
  string,
  string,
  boolean,
  boolean,
  string[],
  number,
][] = [
  [
    "pasta",
    "Pasta integrale",
    "500 g",
    1.49,
    "dry",
    "A0R3",
    "🍝",
    true,
    true,
    ["glutine"],
    180,
  ],
  [
    "rice",
    "Riso basmati",
    "1 kg",
    2.39,
    "dry",
    "A1R3",
    "🍚",
    true,
    true,
    [],
    180,
  ],
  [
    "chickpeas",
    "Ceci biologici",
    "400 g",
    1.29,
    "dry",
    "A2R3",
    "🫘",
    true,
    true,
    [],
    180,
  ],
  [
    "oats",
    "Fiocchi di avena",
    "500 g",
    1.89,
    "dry",
    "A0R5",
    "🌾",
    true,
    true,
    ["glutine"],
    90,
  ],
  [
    "bread",
    "Pane ai cereali",
    "400 g",
    2.19,
    "dry",
    "A1R5",
    "🍞",
    true,
    true,
    ["glutine"],
    4,
  ],
  [
    "tomato",
    "Passata di pomodoro",
    "700 g",
    1.39,
    "dry",
    "A2R5",
    "🥫",
    true,
    true,
    [],
    120,
  ],
  [
    "oil",
    "Olio extravergine",
    "750 ml",
    6.49,
    "heavy",
    "A2R7",
    "🫒",
    true,
    true,
    [],
    180,
  ],
  [
    "water",
    "Acqua naturale",
    "6 × 1,5 l",
    2.49,
    "heavy",
    "A3R8",
    "💧",
    true,
    true,
    [],
    180,
  ],
  [
    "milk",
    "Latte intero",
    "1 l",
    1.39,
    "beverage",
    "A4R3",
    "🥛",
    false,
    true,
    ["latte"],
    30,
  ],
  [
    "oatmilk",
    "Bevanda di avena",
    "1 l",
    1.79,
    "beverage",
    "A4R5",
    "🥛",
    true,
    true,
    ["glutine"],
    30,
  ],
  [
    "coffee",
    "Caffè macinato",
    "250 g",
    3.49,
    "dry",
    "A6R3",
    "☕",
    true,
    true,
    [],
    90,
  ],
  [
    "almonds",
    "Mandorle",
    "200 g",
    2.89,
    "dry",
    "A6R5",
    "🥜",
    true,
    true,
    ["frutta a guscio"],
    60,
  ],
  [
    "spinach",
    "Spinacino fresco",
    "125 g",
    1.59,
    "fresh",
    "A8R2",
    "🥬",
    true,
    true,
    [],
    4,
  ],
  [
    "tomatoes",
    "Pomodorini datterini",
    "500 g",
    2.29,
    "fresh",
    "A8R4",
    "🍅",
    true,
    true,
    [],
    6,
  ],
  [
    "avocado",
    "Avocado",
    "1 pezzo",
    1.49,
    "fresh",
    "A8R6",
    "🥑",
    true,
    true,
    [],
    5,
  ],
  ["carrot", "Carote", "1 kg", 1.29, "fresh", "A9R3", "🥕", true, true, [], 10],
  [
    "zucchini",
    "Zucchine",
    "500 g",
    1.69,
    "fresh",
    "A9R5",
    "🥒",
    true,
    true,
    [],
    6,
  ],
  ["lemon", "Limoni", "500 g", 1.59, "fresh", "A9R7", "🍋", true, true, [], 12],
  [
    "apple",
    "Mele Golden",
    "1 kg",
    2.19,
    "fresh",
    "A8R8",
    "🍎",
    true,
    true,
    [],
    14,
  ],
  ["banana", "Banane", "1 kg", 1.79, "fresh", "A9R9", "🍌", true, true, [], 5],
  [
    "yogurt",
    "Yogurt greco",
    "170 g",
    1.19,
    "fresh",
    "A3R10",
    "🥣",
    false,
    true,
    ["latte"],
    10,
  ],
  [
    "feta",
    "Feta greca",
    "200 g",
    2.39,
    "fresh",
    "A4R10",
    "🧀",
    false,
    true,
    ["latte"],
    12,
  ],
  [
    "eggs",
    "Uova da allevamento a terra",
    "6 pezzi",
    2.29,
    "fresh",
    "A5R10",
    "🥚",
    false,
    true,
    ["uova"],
    14,
  ],
  [
    "chicken",
    "Petto di pollo",
    "400 g",
    4.49,
    "fresh",
    "A6R10",
    "🍗",
    false,
    false,
    [],
    3,
  ],
  [
    "salmon",
    "Filetto di salmone",
    "250 g",
    5.99,
    "fresh",
    "A7R10",
    "🐟",
    false,
    false,
    ["pesce"],
    2,
  ],
  [
    "tofu",
    "Tofu al naturale",
    "200 g",
    2.19,
    "fresh",
    "A8R10",
    "🌱",
    true,
    true,
    ["soia"],
    8,
  ],
  [
    "peas",
    "Piselli surgelati",
    "450 g",
    1.69,
    "frozen",
    "A7R3",
    "🫛",
    true,
    true,
    [],
    90,
  ],
  [
    "berries",
    "Frutti di bosco surgelati",
    "300 g",
    2.99,
    "frozen",
    "A7R5",
    "🫐",
    true,
    true,
    [],
    90,
  ],
  [
    "pizza",
    "Pizza margherita",
    "350 g",
    2.49,
    "frozen",
    "A7R7",
    "🍕",
    false,
    true,
    ["glutine", "latte"],
    90,
  ],
  [
    "icecream",
    "Gelato alla vaniglia",
    "500 g",
    3.29,
    "frozen",
    "A0R8",
    "🍦",
    false,
    true,
    ["latte", "uova"],
    90,
  ],
];
export const products: Product[] = rows.map(
  ([
    id,
    name,
    unit,
    price,
    category,
    node,
    emoji,
    vegan,
    vegetarian,
    allergens,
    days,
  ]) => ({
    id,
    name,
    unit,
    price,
    category,
    node,
    emoji,
    vegan,
    vegetarian,
    allergens,
    days,
    discount: ["chickpeas", "tomatoes", "yogurt", "pasta"].includes(id)
      ? 0.2
      : 0,
    ingredients:
      (
        {
          pasta: "Semola integrale di grano duro, acqua",
          pizza: "Farina di grano, pomodoro, mozzarella (latte), olio, lievito",
          yogurt: "Latte, fermenti lattici",
          tofu: "Soia, acqua, coagulante",
        } as Record<string, string>
      )[id] || name,
    available: id !== "salmon",
  }),
);
export const productById = Object.fromEntries(
  products.map((p) => [p.id, p]),
) as Record<string, Product>;
export interface Recipe {
  id: string;
  name: string;
  subtitle: string;
  minutes: number;
  image: string;
  color: string;
  ingredients: { id: string; qty: number }[];
}
export const recipes: Recipe[] = [
  {
    id: "bowl",
    name: "Bowl mediterranea",
    subtitle: "Colorata, fresca, tutta tua.",
    minutes: 20,
    image: "bowl",
    color: "#e7eee2",
    ingredients: [
      { id: "chickpeas", qty: 1 },
      { id: "spinach", qty: 1 },
      { id: "tomatoes", qty: 1 },
      { id: "avocado", qty: 1 },
    ],
  },
  {
    id: "pasta",
    name: "Pasta al pomodoro",
    subtitle: "Il comfort food di sempre.",
    minutes: 25,
    image: "pasta",
    color: "#fff0df",
    ingredients: [
      { id: "pasta", qty: 1 },
      { id: "tomato", qty: 1 },
      { id: "oil", qty: 0.25 },
    ],
  },
  {
    id: "toast",
    name: "Avocado toast",
    subtitle: "Una pausa che sa di buono.",
    minutes: 10,
    image: "toast",
    color: "#ecf0df",
    ingredients: [
      { id: "bread", qty: 1 },
      { id: "avocado", qty: 1 },
      { id: "eggs", qty: 0.5 },
    ],
  },
  {
    id: "porridge",
    name: "Porridge ai frutti di bosco",
    subtitle: "Il buongiorno, in una ciotola.",
    minutes: 10,
    image: "bowl",
    color: "#f5e9ed",
    ingredients: [
      { id: "oats", qty: 0.5 },
      { id: "oatmilk", qty: 0.5 },
      { id: "berries", qty: 0.5 },
    ],
  },
  {
    id: "rice",
    name: "Riso verde con tofu",
    subtitle: "Semplice e ricco di colore.",
    minutes: 25,
    image: "bowl",
    color: "#e8eee1",
    ingredients: [
      { id: "rice", qty: 0.5 },
      { id: "tofu", qty: 1 },
      { id: "zucchini", qty: 1 },
      { id: "peas", qty: 0.5 },
    ],
  },
  {
    id: "salad",
    name: "Insalata greca",
    subtitle: "Un piccolo viaggio in Grecia.",
    minutes: 15,
    image: "bowl",
    color: "#eef0de",
    ingredients: [
      { id: "tomatoes", qty: 1 },
      { id: "feta", qty: 1 },
      { id: "lemon", qty: 0.5 },
    ],
  },
  {
    id: "chicken",
    name: "Pollo al limone",
    subtitle: "La cena si fa leggera.",
    minutes: 30,
    image: "pasta",
    color: "#faf0dc",
    ingredients: [
      { id: "chicken", qty: 1 },
      { id: "lemon", qty: 0.5 },
      { id: "carrot", qty: 0.5 },
    ],
  },
  {
    id: "soup",
    name: "Vellutata di carote",
    subtitle: "Calda, morbida, zero sprechi.",
    minutes: 30,
    image: "bowl",
    color: "#fff0de",
    ingredients: [
      { id: "carrot", qty: 1 },
      { id: "chickpeas", qty: 1 },
      { id: "oil", qty: 0.1 },
    ],
  },
];
export const defaultProfile: Profile = {
  name: "Sofia",
  diet: "Vegetariana",
  allergies: [],
  budget: 50,
  goal: "Meno sprechi",
};
export const categoryLabels: Record<Category, string> = {
  heavy: "Pesanti",
  dry: "Dispensa",
  beverage: "Bevande",
  fresh: "Freschi",
  frozen: "Surgelati",
};
export const stores = [
  {
    id: "lidl",
    name: "Lidl",
    address: "Il tuo supermercato demo",
    distance: "0,8 km",
    factor: 1,
    missing: [] as string[],
    color: "#edf3fb",
  },
  {
    id: "coop",
    name: "Coop",
    address: "Punto vendita di esempio",
    distance: "1,4 km",
    factor: 1.12,
    missing: ["avocado", "tofu"],
    color: "#fff0ed",
  },
  {
    id: "conad",
    name: "Conad",
    address: "Punto vendita di esempio",
    distance: "2,1 km",
    factor: 1.07,
    missing: ["spinach"],
    color: "#fff5df",
  },
];
